### ISSUE TITLE
resp.asserted-states is not iterable

### ISSUE THREAD

**Issue by hansyulian** [facebook/metro#1022]
**Do you want to request a *feature* or report a *bug*?**
- Bug or maybe support

**What is the current behavior?**
fresh initialization of react native with expo and native code have the same problem:
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: resp.asserted-states is not iterable
    at Object.onSubscribe [as cb] (D:\Sources\Personal\hauthenticator\node_modules\metro-file-map\src\watchers\WatchmanWatcher.js:174:31)
    at BunserBuf.<anonymous> (D:\Sources\Personal\hauthenticator\node_modules\fb-watchman\index.js:103:15)
    at BunserBuf.emit (node:events:513:28)
    at BunserBuf.process (D:\Sources\Personal\hauthenticator\node_modules\bser\index.js:292:10)
    at D:\Sources\Personal\hauthenticator\node_modules\bser\index.js:247:12
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Emitted 'error' event on WatchmanWatcher instance at:
    at Client.<anonymous> (D:\Sources\Personal\hauthenticator\node_modules\metro-file-map\src\watchers\WatchmanWatcher.js:107:12)       
    at Client.emit (node:events:513:28)
    at BunserBuf.<anonymous> (D:\Sources\Personal\hauthenticator\node_modules\fb-watchman\index.js:111:12)
    at BunserBuf.emit (node:events:513:28)
    at D:\Sources\Personal\hauthenticator\node_modules\bser\index.js:249:12
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.16.1
```
tried with nodejs 16 also same problem, but existing react native project doesn't have this issue

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by robhogan** [comment]
Hi @hansyulian, thanks for the report. Looks like this could be a difference with Watchman on Windows (vs macOS). Would you be able to check `watchman --version` and `watchman list-capabilities` and let me know the output? Thanks.

**Comment by hansyulian** [comment]
In my windows:
- ```watchman --version```
```
4.9.4
```
- ```watchman list-capabilities```
```
{
    "version": "4.9.4",
    "capabilities": [
        "cmd-debug-contenthash",
        "cmd-debug-symlink-target-cache",
        "term-not",
        "bser-v2",
        "cmd-debug-poison",
        "field-mtime",
        "cmd-shutdown-server",
        "field-mtime_us",
        "cmd-get-pid",
        "term-true",
        "suffix-set",
        "term-anyof",
        "term-false",
        "term-allof",
        "cmd-since",
        "term-dirname",
        "cmd-watch-list",
        "term-type",
        "term-idirname",
        "cmd-get-config",
        "dedup_results",
        "term-exists",
        "term-empty",
        "scm-since",
        "field-gid",
        "field-name",
        "term-imatch",
        "field-content.sha1hex",
        "field-symlink_target",
        "field-size",
        "field-exists",
        "field-atime_us",
        "field-atime_ns",
        "field-mode",
        "field-uid",
        "cmd-debug-drop-privs",
        "field-atime",
        "field-atime_ms",
        "term-match",
        "field-atime_f",
        "term-since",
        "field-ctime",
        "field-mtime_ms",
        "field-ino",
        "field-mtime_ns",
        "cmd-version",
        "field-mtime_f",
        "cmd-find",
        "field-ctime_ms",
        "field-ctime_us",
        "field-ctime_ns",
        "field-ctime_f",
        "field-dev",
        "wildmatch",
        "field-nlink",
        "field-new",
        "field-cclock",
        "field-oclock",
        "field-type",
        "glob_generator",
        "term-name",
        "term-size",
        "term-suffix",
        "wildmatch-multislash",
        "term-iname",
        "relative_root",
        "cmd-debug-recrawl",
        "cmd-debug-get-asserted-states",
        "cmd-debug-show-cursors",
        "cmd-debug-ageout",
        "cmd-clock",
        "cmd-debug-set-subscriptions-paused",
        "cmd-watch-del-all",
        "cmd-debug-get-subscriptions",
        "cmd-list-capabilities",
        "cmd-get-sockname",
        "cmd-log-level",
        "cmd-watch-del",
        "cmd-log",
        "cmd-query",
        "cmd-flush-subscriptions",
        "cmd-unsubscribe",
        "cmd-watch-project",
        "cmd-subscribe",
        "cmd-trigger-del",
        "cmd-trigger-list",
        "cmd-trigger",
        "clock-sync-timeout",
        "cmd-watch",
        "saved-state-local",
        "scm-hg",
        "watcher-win32",
        "cmd-state-enter",
        "cmd-state-leave"
    ]
}
```

**Comment by hansyulian** [comment]
Comparing with my mac: 
- ```watchman --version```
```
2023.04.17.00
```
- ``` watchman list-capabilities```
```
{
    "version": "2023.04.17.00",
    "capabilities": [
        "cmd-debug-kqueue-and-fsevents-recrawl",
        "watcher-kqueue",
        "watcher-eden",
        "scm-git",
        "cmd-watch",
        "cmd-watch-del-all",
        "cmd-watch-del",
        "clock-sync-timeout",
        "watcher-fsevents",
        "cmd-trigger",
        "cmd-trigger-list",
        "cmd-trigger-del",
        "cmd-state-leave",
        "cmd-state-enter",
        "cmd-since",
        "cmd-global-log-level",
        "cmd-log",
        "cmd-list-capabilities",
        "cmd-find",
        "cmd-version",
        "cmd-debug-contenthash",
        "cmd-unsubscribe",
        "cmd-debug-watcher-info",
        "cmd-debug-status",
        "cmd-debug-fsevents-inject-drop",
        "cmd-debug-get-subscriptions",
        "cmd-debug-set-subscriptions-paused",
        "cmd-debug-set-parallel-crawl",
        "cmd-debug-drop-privs",
        "dedup_results",
        "relative_root",
        "cmd-clock",
        "wildmatch-multislash",
        "wildmatch",
        "glob_generator",
        "cmd-subscribe",
        "cmd-debug-ageout",
        "field-mode",
        "field-symlink_target",
        "field-dev",
        "field-gid",
        "cmd-debug-symlink-target-cache",
        "cmd-debug-root-status",
        "cmd-debug-get-asserted-states",
        "cmd-debug-poison",
        "field-name",
        "field-atime_ms",
        "field-uid",
        "field-exists",
        "field-nlink",
        "field-atime_ns",
        "field-ctime_us",
        "field-mtime_ns",
        "field-atime",
        "field-ctime_ms",
        "field-atime_f",
        "suffix-set",
        "field-size",
        "field-mtime",
        "field-mtime_f",
        "field-ctime_ns",
        "field-ctime_f",
        "cmd-get-log",
        "cmd-get-sockname",
        "field-mtime_us",
        "field-ino",
        "field-atime_us",
        "saved-state-local",
        "field-oclock",
        "field-cclock",
        "cmd-watch-project",
        "cmd-debug-recrawl",
        "field-type",
        "cmd-watch-list",
        "field-ctime",
        "field-content.sha1hex",
        "scm-since",
        "term-type",
        "term-true",
        "field-mtime_ms",
        "term-suffix",
        "term-size",
        "term-since",
        "cmd-debug-watcher-info-clear",
        "term-not",
        "cmd-log-level",
        "cmd-get-config",
        "term-match",
        "term-ipcre",
        "term-pcre",
        "term-name",
        "term-iname",
        "watcher-kqueue+fsevents",
        "cmd-debug-show-cursors",
        "term-imatch",
        "term-idirname",
        "term-false",
        "field-new",
        "term-exists",
        "cmd-flush-subscriptions",
        "cmd-query",
        "term-empty",
        "term-dirname",
        "term-anyof",
        "term-allof",
        "scm-hg",
        "bser-v2",
        "cmd-get-pid",
        "cmd-shutdown-server"
    ]
}
```

**Comment by hansyulian** [comment]
closing the issue, upgrading watchman fixed the problem
