### ISSUE TITLE
SHA-1 for file C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro-runtime\src\polyfills\require.js is not computed.

### ISSUE THREAD

**Issue by SitaMelark** [facebook/metro#1139]
When trying to run : `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` to generate the debug apk im getting the following error: 
```
error SHA-1 for file C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro-runtime\src\polyfills\require.js (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro-runtime\src\polyfills\require.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
ReferenceError: SHA-1 for file C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro-runtime\src\polyfills\require.js (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro-runtime\src\polyfills\require.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
    at DependencyGraph.getSha1 (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph.js:217:13)
    at Transformer._getSha1 (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\Bundler.js:26:26)
    at Transformer.transformFile (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\Transformer.js:106:19)
    at Bundler.transformFile (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\Bundler.js:60:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\lib\transformHelpers.js:143:12)
    at async Graph._processModule (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:257:20)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Promise.all (index 0)
    at async Graph.initialTraverseDependencies (C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:233:5)
```
also, when i generate the realeased app, the post methods arent working but in debug mode does (connected to computer and `npm start`). Heres my post (cant show the ip):
```
const url = "http://159.--.---.---:8095/API/mobile";

export const sendData = async (usuario: string, contraseña: string) => {

  try {
    const response = await fetch(url + '/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ usuario, contraseña }),
    });

    const result = await response.text();


    if (response.ok && result != "") {

      return result;
    } else if (response.status === 204) {
      return "LoginError";
    } else {
      return "ServerError";
    }
  } catch (error) {
    console.error(error);
    return "ServerError";
  }
};
```

Edit: For some reason i have no android/app/src/main/assets/index.android.bundle file, is there a way to generate it?

**Comment by SitaMelark** [comment]
Ok so the way to solve the issue to get the debug apk is the following:
1. Got to android directory : `cd android`
2. Do a gradlew clean: `.\gradlew clean`
3. Go back: `cd ..`
4. Create a folder called `assets` in `/android/app/src/main/` directory
5. In the main directory do `npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
6. Go again to android folder: `cd android`
7. Create the app doing assemble: `.\gradlew assembleDebug`
8. Find the apk in the folder: `/android/app/build/outputs/apk/debug`

Ill go check if this fixed the realeased app issue

**Comment by robhogan** [comment]
> `C:\Users\Eportal\AppData\Roaming\npm\node_modules\react-native`

This looks wrong - `react-native` should be installed as a dependency of your project, this looks like it's installed globally (in a location Metro isn't configured to watch, hence the error resolving `metro-runtime`). What's your project structure?
