### ISSUE TITLE
bundling failed: TypeError: Property body[10] of BlockStatement expected node to be of a type ["Statement"] but instead got "Noop"

### ISSUE THREAD

**Issue by DaKaZ** [facebook/metro#116]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I recently upgraded to react-native@0.52.0 with metro@0.24.3 and I can no longer deliver bundles to iOS or Android.

This repo exhibits the issue: https://github.com/DaKaZ/metro-test-app

```
error: bundling failed: TypeError: Property body[10] of BlockStatement expected node to be of a type ["Statement"] but instead got "Noop"
    at validate (~/client/node_modules/babel-types/lib/definitions/index.js:109:13)
    at validator (~/client/node_modules/babel-types/lib/definitions/index.js:57:7)
    at Object.validate (~/client/node_modules/babel-types/lib/definitions/index.js:190:10)
    at validate (~/client/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (~/client/node_modules/babel-types/lib/index.js:466:7)
    at functionFromProgram (~/client/node_modules/metro/src/ModuleGraph/worker/JsFileWrapping.js:48:5)
    at Object.wrapModule (~/client/node_modules/metro/src/ModuleGraph/worker/JsFileWrapping.js:25:19)
    at postTransform (~/client/node_modules/metro/src/JSTransformer/worker/index.js:140:33)
    at Object.transformCode [as transform] (~/client/node_modules/metro/src/JSTransformer/worker/index.js:220:17)
```

**What is the expected behavior?**
The bundle should be compiled and delivered to the client

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
I am running on macOS 10.12.6, node 9.2.1, yarn 1.32 and npm 5.6.0.

**Comment by DaKaZ** [comment]
Sorry this is a non issue - it was the old bablerc file, I just removed it and now all is working.

**Comment by yanni4night** [comment]
@DaKaZ Would you please explain how to solve it?

**Comment by DaKaZ** [comment]
Just delete the .bablerc file.

**Comment by haggholm** [comment]
Do you mean your project’s top-level `.babelrc`? I’m getting this error (or virtually the same), and for me, deleting the project `.babelrc` is not an option. If you mean some other `.babelrc`, what? where?

**Comment by seemavora** [comment]
Did anyone figure this issue out? My project does not have a .bablerc either.
