### ISSUE TITLE
Metro-core fails to build if a legacy version of Lodash is installed

### ISSUE THREAD

**Issue by carnye** [facebook/metro#122]
Reproduction steps:
1. Create a new react native project
2. Install lodash@3.10.1
3. Run `npm run start`

The following error appears:
```
Error: Cannot find module 'lodash/throttle'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/metro-core/src/Terminal/Terminal.js:16:18)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Comment by rafeca** [comment]
Thanks for reporting and for the clear repro steps! I've been able to reproduce it and I'm going to send a fix soon 😄

**Comment by rafeca** [comment]
This should have been fixed by https://github.com/facebook/metro/commit/a0d15e0d25c3a255514c73d1f028bc9c3a034b3b I'll release a new metro version this week
