### ISSUE TITLE
Dependencies missing from metro-core/package.json

### ISSUE THREAD

**Issue by lukewis** [facebook/metro#130]
I have a new react-native project (react-native init) that is failing to bundle due to missing the wordwrap npm package.  Not sure if that's the only missing dependency, or if there are others?  This is very similar to #119, but I assume that issue is refering to the root metro/package.json as oppsed to metro-core.

`
/usr/local/bin/node /<path omitted>/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /<path omitted>/main.jsbundle --assets-dest /<path omitted>/app.app
2018-01-31T13:35:20.0701510Z module.js:327
2018-01-31T13:35:20.0716130Z     throw err;
2018-01-31T13:35:20.0728700Z     ^
2018-01-31T13:35:20.0734330Z 
2018-01-31T13:35:20.0747380Z Error: Cannot find module 'wordwrap'
2018-01-31T13:35:20.0762930Z     at Function.Module._resolveFilename (module.js:325:15)
2018-01-31T13:35:20.0775520Z     at Function.Module._load (module.js:276:25)
2018-01-31T13:35:20.0787030Z     at Module.require (module.js:353:17)
2018-01-31T13:35:20.0805620Z     at require (internal/module.js:12:17)
2018-01-31T13:35:20.0828580Z     at Object.<anonymous> (/<path omitted>/node_modules/react-native/node_modules/metro-core/src/formatBanner/formatBanner.js:17:16)
2018-01-31T13:35:20.0852160Z     at Module._compile (module.js:409:26)
2018-01-31T13:35:20.0871980Z     at Object.Module._extensions..js (module.js:416:10)
2018-01-31T13:35:20.0892230Z     at Module.load (module.js:343:32)
2018-01-31T13:35:20.0983570Z     at Function.Module._load (module.js:300:12)
2018-01-31T13:35:20.1003850Z     at Module.require (module.js:353:17)
`

**Comment by rafeca** [comment]
Closing this issue, since it was already fixed :)

**Comment by lukewis** [comment]
Thanks @rafeca !  Just leaving a paper trail to where this was fixed :) https://github.com/facebook/metro/commit/d7165e5cbbade7262832b28d69c2b8fd463216fc
