### ISSUE TITLE
Error: EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by Irfanwani** [facebook/metro#1405]
**Bug Report**
I upgraded the app to the new arch (0.76.x) and now I am getting this error when trying to archive in xcode:
```

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on NodeWatcher instance at:
    at FSWatcher._checkedEmitError (node_modules/metro-file-map/src/watchers/NodeWatcher.js:82:12)
    at FSWatcher.emit (node:events:513:28)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
```

**What is the current behavior?**
App works fine, in dev as well as in release mode on both android as well as in iOS. First i was getting this error in terminal too when running `npm start` but that was fixed by deleting node_modules and reinstalling deps but archiving is still throwing this error.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Set Run scheme to Release and change run destination to Any iOS device, and try to archive. 

**What is the expected behavior?**
Archive should be executed successfully instead of throwing a metro bundler error.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
metro - v0.81.0
node - v22.11.0
npm - v10.9.0
react-native - 0.76

**Comment by Irfanwani** [comment]
Fixed it by upgrading all the packages (except react, kept it at 18.x as react native doesn't support 19.x yet), though my packages were just a little behind the latest versions, it worked, deleted node_modules, pods and resintalled them .

**Comment by codingslash76** [comment]
@Irfanwani I am getting the same error (unable to make archieve) as you mentioned. Below is the package.json and react-native info I am using. Can you please help me what I am missing here?

```
System:
  OS: macOS 15.2
  CPU: (8) arm64 Apple M1
  Memory: 179.06 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.4.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.9.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.3.6
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: ^0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

```
{
  
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.7.1",
    "@fortawesome/free-brands-svg-icons": "^6.7.1",
    "@fortawesome/free-solid-svg-icons": "^6.7.1",
    "@fortawesome/pro-duotone-svg-icons": "^6.7.1",
    "@fortawesome/pro-light-svg-icons": "^6.7.1",
    "@fortawesome/pro-regular-svg-icons": "^6.7.1",
    "@fortawesome/pro-solid-svg-icons": "^6.7.1",
    "@fortawesome/react-native-fontawesome": "^0.3.2",
    "@fortawesome/sharp-light-svg-icons": "^6.7.1",
    "@fortawesome/sharp-regular-svg-icons": "^6.7.1",
    "@gorhom/bottom-sheet": "^4.6.4",
    "@react-native-async-storage/async-storage": "^2.1.0",
    "@react-native-camera-roll/camera-roll": "^7.9.0",
    "@react-native-community/blur": "^4.4.1",
    "@react-native-community/datetimepicker": "^8.2.0",
    "@react-native-community/geolocation": "^3.4.0",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-community/slider": "^4.5.5",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/messaging": "^18.7.3",
    "@react-native-picker/picker": "^2.4.0",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/stack": "^6.4.1",
    "@stripe/stripe-react-native": "^0.38.4",
    "axios": "^1.7.2",
    "buffer": "^6.0.3",
    "deprecated-react-native-prop-types": "^2.3.0",
    "fbjs": "^3.0.5",
    "js-sha256": "^0.11.0",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "native-base": "^3.4.28",
    "prop-types": "^15.8.1",
    "react": "18.3.1",
    "react-native": "^0.76.5",
    "react-native-add-calendar-event": "^5.0.0",
    "react-native-blob-util": "^0.19.11",
    "react-native-camera": "^4.2.1",
    "react-native-detector": "^0.2.3",
    "react-native-document-picker": "^9.3.1",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "^2.21.2",
    "react-native-image-crop-picker": "^0.41.6",
    "react-native-image-picker": "^7.2.2",
    "react-native-image-viewing": "^0.2.2",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-maps": "^1.20.1",
    "react-native-masonry-list": "^2.16.2",
    "react-native-media-controls": "^2.3.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^18.0.0",
    "react-native-nfc-manager": "^3.16.1",
    "react-native-pdf": "^6.7.6",
    "react-native-permissions": "^5.2.1",
    "react-native-picker-select": "^9.3.1",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-native-qrcode-svg": "^6.3.12",
    "react-native-quick-actions": "^0.3.13",
    "react-native-reanimated": "^3.15.0",
    "react-native-safe-area-context": "^5.0.0",
    "react-native-screens": "^4.3.0",
    "react-native-share": "^12.0.3",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sound": "^0.11.2",
    "react-native-svg": "^15.10.1",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-swiper": "^1.6.0",
    "react-native-switch-selector": "^2.3.0",
    "react-native-webview": "^13.12.5",
    "react-native-zohodesk-portal-sdk": "^1.3.6",
    "react-redux": "^9.1.2",
    "redux": "^5.0.1",
    "rive-react-native": "^7.3.0",
    "rn-range-slider": "github:githuboftigran/rn-range-slider#v1"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@eslint/compat": "^1.2.4",
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.76.5",
    "@react-native/eslint-config": "0.76.5",
    "@react-native/metro-config": "0.76.5",
    "@react-native/typescript-config": "0.76.5",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "@welldone-software/why-did-you-render": "^8.0.3",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^9.16.0",
    "jest": "^29.6.3",
    "patch-package": "^8.0.0",
    "prettier": "^3.4.2",
    "react-devtools": "^5.3.1",
    "react-devtools-core": "^5.3.1",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.5.4"
  },
  "engines": {
    "node": ">=18"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  }
}

```

**Comment by codingslash76** [comment]
![Screenshot 2024-12-17 at 11 24 07 AM](https://github.com/user-attachments/assets/08b89cfa-0771-4ab2-87c1-dce7e8c38ee2)
![Screenshot 2024-12-17 at 11 23 55 AM](https://github.com/user-attachments/assets/fb412d69-cfc1-4c35-b8cd-189fcf8e45f5)

**Comment by Irfanwani** [comment]
@codingslash76 for me it was the packages, delete node_modules, upgrade your packages, delete pods and reinstall all dependencies (npm i, cd ios, pod install). It should fix the issue

**Comment by codingslash76** [comment]
@Irfanwani Thanks for the response.

I have attempted all the steps multiple times without success, even after resetting the entire system.

I have created the following issue.
https://github.com/facebook/react-native/issues/48304

**Comment by Irfanwani** [comment]
Did you reinstalled watchman (and delete its cache).

**Comment by codingslash76** [comment]
Yes, Multiple times. 
It's working fine on simulator (Android and IOS) but the error is there only while creating release build for both OS.

**Comment by robhogan** [comment]
I'm surprised to see `NodeWatcher` being used on macOS - typically it should be using `FSEventsWatcher` if the `fsevents` optional dependency is installed.

Do you have `fsevents` in your `node_modules`?

**Comment by quifago** [comment]
I'm facing the same error:

```
node:events:502
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSWatcher._handle.onchange (node:internal/fs/watchers:207:21)
Emitted 'error' event on NodeWatcher instance at:
    at FSWatcher._checkedEmitError (/Users/quique/Developer/with-openai/node_modules/metro-file-map/src/watchers/NodeWatcher.js:82:12)
    at FSWatcher.emit (node:events:524:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:213:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}

Node.js v22.13.0
```

And nope, I don't have `fsevents` in my `node_modules`.

**Comment by robhogan** [comment]
`fsevents` is no longer a dependency as of 0.81.1 (yesterday), and the watcher behaviour has been tweaked to hopefully mitigate this.

If folks are still seeing this with Metro 0.81.1, could you mention whether you have Watchman installed, whether you have a monorepo setup, and whether it's a big/small (corporate/hobby) project? (Or concretely, approx number of files under configured `watchFolders`, including the project root)

Running Metro with `DEBUG=Metro:*` and pasting the terminal output would also be very helpful.

**Comment by marcodafonseca** [comment]
> I'm facing the same error:
> 
> ```
> node:events:502
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EMFILE: too many open files, watch
>     at FSWatcher._handle.onchange (node:internal/fs/watchers:207:21)
> Emitted 'error' event on NodeWatcher instance at:
>     at FSWatcher._checkedEmitError (/Users/quique/Developer/with-openai/node_modules/metro-file-map/src/watchers/NodeWatcher.js:82:12)
>     at FSWatcher.emit (node:events:524:28)
>     at FSWatcher._handle.onchange (node:internal/fs/watchers:213:12) {
>   errno: -24,
>   syscall: 'watch',
>   code: 'EMFILE',
>   filename: null
> }
> 
> Node.js v22.13.0
> ```
> 
> And nope, I don't have `fsevents` in my `node_modules`.
> 
> It looks like `watchman` is not initiated.
> 
> Just running the the `watchman` command, with no arguments or whatsoever, fixes it. But it happens again next time I restart the computer (MacOS).

@quifago - You deserve a giant, delicious, and moist chocolate cake! Thanks for pointing this out!

**Comment by JASIM0021** [comment]
# Fix for "EMFILE: too many open files" Issue in Expo on macOS

If you're encountering the `EMFILE: too many open files, watch` error in Expo on macOS, follow these steps to fix the issue:

## Step 1: Install `watchman`

First, make sure that `watchman` is installed:

```bash
brew install watchman
```

## Step 2: Increase the Watcher Limit

Ensure that the watch limit is properly set:

```bash
ulimit -n 9999999
```

## Step 3: Delete `node_modules` and `package-lock.json`

Delete the `node_modules` directory and `package-lock.json` file to ensure a fresh installation of packages:

```bash
rm -rf node_modules && rm package-lock.json
```

## Step 4: Install Packages

Install the dependencies again:

```bash
npm install
```

## Step 5: Upgrade `watchman` (If Needed)

Make sure `watchman` is up-to-date:

```bash
brew upgrade watchman
```

## Step 6: Create `metro.config.js`

Create a `metro.config.js` file in the root of your project and add the following configuration:

```js
const exclusionList = require('metro-config/src/defaults/exclusionList');

module.exports = {
  resolver: {
    blockList: exclusionList([
      /node_modules/,
      /build/
    ])
  }
};
```

## Step 7: Shutdown `watchman`

Stop the `watchman` server:

```bash
watchman shutdown-server
```

## Step 8: Clear Expo's Cache

Clear Expo's cache to reset any internal issues:

```bash
expo start -c
```

---

This should resolve the "too many open files" issue in Expo. Let me know if you face any other problems!

**Comment by petertoth-dev** [comment]
Sometimes it's not about `watchman` even if the error tells that:

If you've already tried everything (restart, clean build, watchman install, watchman reinstall, increase watcher limit etc....), your case might be similar to mine, and you don't have `node` in `PATH` for the Xcode environment.

Xcode -> Build Phases -> Scroll down to "Bundle React Native code and images", and add `node` to `PATH`:
`export PATH=$PATH:/opt/homebrew/bin`

In case your `node` is in a different path (e.g. you installed it with nvm), check your node's PATH and add it to PATH like above.

To check your node's path, open terminal and `which node` should tell you the path.

`export PATH=$PATH:/path/to/your/node/folder`

**Comment by JASIM0021** [comment]
agree 

```
export PATH=$PATH:/path/to/your/node/folder
```

This step is important. Thank you for your attention to this information!

**Comment by kevingo710** [comment]
My fix: downgrade node version from v23.9.0 to -> v18.20.7 reinstall node_modules, run and enjoy!

**Comment by robhogan** [comment]
Very interesting that a couple of folks say this affected by Node.js version. 

Is that reproducible, so switching Node versions breaks/fixes it *without doing anything else* like installing node_modules?

Any help appreciated folks - I see a lot of people running into this but the fixes are inconsistent and I've yet to be able to repro.

**Comment by robhogan** [comment]
> module.exports = {
>   resolver: {
>     blockList: exclusionList([
>       /node_modules/,
>       /build/
>     ])
>   }
> };

Appreciate the suggestion but adding `node_modules` to the blockList is **not** recommended and will break resolution.

**Comment by vinjana** [comment]
I got exactly this error with VSCodium (installed via Snap on Ubuntu 24.04):

This helped:

```
fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=512
```

Compare [the original](https://stackoverflow.com/a/64941113).

**Comment by JustSuperHuman** [comment]
I got this error non-stop on Windows 11 + Bun + Expo 55/56 - nothing seems to work.
thought I'd share this hack - just asked claude to build a script that automatically restarts the server any time the error occurs. Works pretty well IMO. 

<img width="1628" height="901" alt="Image" src="https://github.com/user-attachments/assets/bd07b754-f59b-4eb0-b57d-d74e64e7eb11" />

**Comment by jerrym7** [comment]
## Fix: EXPO Metro EMFILE "too many open files"

**File:** `metro.config.js`

### Changed from

```js
config.watchFolders = [path.resolve(__dirname)];
```

### Changed to

```js
const CACHE_IO_CONCURRENCY = Number(process.env.METRO_CACHE_CONCURRENCY) || 64;

function createLimiter(max) {
  let active = 0;
  const queue = [];

  const drain = () => {
    while (active < max && queue.length > 0) {
      const { fn, resolve, reject } = queue.shift();
      active++;
      Promise.resolve()
        .then(fn)
        .then(resolve, reject)
        .then(() => {
          active--;
          drain();
        });
    }
  };

  return (fn) =>
    new Promise((resolve, reject) => {
      queue.push({ fn, resolve, reject });
      drain();
    });
}

async function withRetry(fn, attempts = 6) {
  for (let attempt = 0; ; attempt++) {
    try {
      return await fn();
    } catch (err) {
      const code = err && err.code;
      if ((code !== "EMFILE" && code !== "ENFILE") || attempt >= attempts) {
        throw err;
      }
      await new Promise((r) => setTimeout(r, 20 * 2 ** attempt));
    }
  }
}

const limitCacheIO = createLimiter(CACHE_IO_CONCURRENCY);

if (Array.isArray(config.cacheStores)) {
  for (const store of config.cacheStores) {
    for (const method of ["get", "set"]) {
      const original = store[method];
      if (typeof original !== "function") continue;
      store[method] = (...args) =>
        limitCacheIO(() => withRetry(() => original.apply(store, args)));
    }
  }
}
```

### Why

**Deleting the line:** Metro already watches the project folder automatically.
That line told it to watch the same folder a second time, so it scanned and
watched many files files in `node_modules` twice for nothing.

**Adding the code:** Expo's build cache opens one file per module, and it opens
them all at the same time.

**Comment by MOHAMED-LAAGUILI** [comment]
## I found a solution the code below worked for me by Claude
All I needed is to set watchman to true and define the block list from config.resolver.

```

process.env.EXPO_ROUTER_APP_ROOT = './app';
process.env.EXPO_ROUTER_IMPORT_MODE = 'sync';

const { getDefaultConfig } = require('expo/metro-config');
const { withUniwindConfig } = require('uniwind/metro');

const config = getDefaultConfig(__dirname);

// Expo CLI defaults `useWatchman` to false, so on Windows Metro falls back to
// Node's fs.watch and dies with "EMFILE: too many open files, watch" on large
// trees. Watchman is a documented prerequisite for this template (see README).
config.resolver.useWatchman = true;

// Never crawl/watch native build output or VCS internals from the project root.
const escapeForRegExp = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const rootDir = escapeForRegExp(__dirname);
const blockedPatterns = [
  config.resolver.blockList,
  new RegExp(`^${rootDir}[\\\\/](android|ios|dist|build)[\\\\/].*`),
  new RegExp(`^${rootDir}[\\\\/]\\.git[\\\\/].*`),
].flat().filter(Boolean);
config.resolver.blockList = new RegExp(
  blockedPatterns.map(pattern => (pattern instanceof RegExp ? pattern.source : pattern)).join('|'),
);


module.exports = withUniwindConfig(config, {
  cssEntryFile: './global.css',
  dtsFile: './uniwind-types.d.ts',
});

```
