### ISSUE TITLE
Metro fails with react-i18next

### ISSUE THREAD

**Issue by SkyzohKey** [facebook/metro#145]
Hey guys, I'm currently working on a project that is platfom-agnostic (react-native-web) with my own components and stuff, and I'd like to add i18next to the project. So it works fine on the web/desktop builds (react) but when it comes to mobile (react-native), the following error happens in Metro:

```js
error: bundling failed: Error: While trying to resolve module `react-i18next` from file `/home/skyzohkey/Dev/React/Tox-Universal-Client/App.js`, the package `/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/dist/commonjs/index.js`. Indeed, none of these files exist:

  * `/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/dist/commonjs/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/dist/commonjs/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:104:15)
    at DependencyGraph.resolveDependency (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
    at <anonymous>
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/4), failed.

```

If reported the issue on i18next repo too.

You can try yourself to reproduce by cloning my repository here: https://github.com/Tox-Client/client/

Thanks in advance guys, I've tried all I can do before opening that issue and I hope you will be better than me at finding the issue c:

**Comment by rafeca** [comment]
Can you check that at least one of the projectRoots passed to metro include the folder where `react-i18next` is installed? To check the projectRoots, you can look at the terminal output after starting metro:

```
Looking for JS files in
   /home/.../folderA
   /home/.../folderB
```

If it doesn't you'll need to add that folder to the projectRoots, so metro can resolve its files correctly

**Comment by SkyzohKey** [comment]
Ok here's the output so I assume it does have the correct projectRoots. :/

```
[skyzohkey@skyzohkey-pc Tox-Universal-Client]$ react-native start
Scanning folders for symlinks in /home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules (34ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /home/skyzohkey/Dev/React/Tox-Universal-Client 


Metro Bundler ready.
```

**Comment by rafeca** [comment]
aha! the issue comes from your [blacklist config param](https://github.com/Tox-Client/client/blob/master/rn-cli.config.js#L5), you're telling metro to ignore any JS file in a `dist/` folder.

Can you try changing that and check if the error disappears?

**Comment by SkyzohKey** [comment]
Yep because the dist/ folder is electron-builder related, not react-native :/

**Comment by rafeca** [comment]
Can you make that regexp more restrictive then to not pass on `node_modules/react-i18next/dist/commonjs/index.js`?

**Comment by SkyzohKey** [comment]
Mh, i will try. Lemme check ;)

**Comment by SkyzohKey** [comment]
Ok let's close this issue. I've removed the `dist/` folder and passed `"output": "packages/"` to electron-builder. Thanks for the help man, sometimes issues are just dumbness (from me xD).
