### ISSUE TITLE
Unable to resolve module that is present

### ISSUE THREAD

**Issue by s-nel** [facebook/metro#155]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Getting "unable to resolve module" for a module that _is_ present:

```
error: bundling failed: Error: Unable to resolve module `../../../../React` from `/work/project/node_modules/react-native/Libraries/Components/CheckBox/CheckBox.android.js`: The module `../../../../React` could not be found from `/work/project/node_modules/react-native/Libraries/Components/CheckBox/CheckBox.android.js`. Indeed, none of these files exist:

  * `/work/project/node_modules/React(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/work/project/node_modules/React/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/work/project/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/work/project/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/work/project/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/work/project/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/work/project/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /work/project/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/work/project/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /work/project/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
```

One of the candidate files that Metro claims was not found is there:

```
$ ls -al /work/project/node_modules/React/index.js
-rw-r--r--  1 ...
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

I'll prepare one presently.

**What is the expected behavior?**

Metro should be able to find the module that it claims it can't resolve.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Reproduced on react-native 0.54.2 with Metro version 0.28.0 and latest react-native commit with Metro version 0.30.1.

Metro versions: 0.28.0, 0.30.1

Node version: 9.3.0

Npm version: 5.7.1

Yarn version: 1.5.1

Mac OS X High Sierra: 10.13.3

**Comment by s-nel** [comment]
I think this was caused by having to different Metro's in `node_modules`

**Comment by Dhrupal** [comment]
@s-nel  What you have removed?
