### ISSUE TITLE
[master iOS]Metro Bundler has encountered an internal error, please check your terminal error output for more details

### ISSUE THREAD

**Issue by ShiYongjieGitHub** [facebook/metro#175]
This is all the relevant information of the terminal error:
Looking for JS files in
/Users/shiyongjie/Desktop/Git/Facebook/react-native

Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: ReferenceError: SHA-1 for file /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/react/index.js is not computed
at DependencyGraph.getSha1 (/Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:224:3541)
at /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:263:56
at Generator.next ()
at step (/Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:11:657)
at /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:11:817
at 
at process._tickCallback (internal/process/next_tick.js:169:7)
BUNDLE [ios, dev] RNTester/js/RNTesterApp.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/2), failed.

And this is all all the relevant information of device red screen showing:
Metro Bundler has encountered an internal error, please check your terminal error output for more details

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF

CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
# #

**Comment by rafeca** [comment]
Thanks for reporting! We're aware of the issue, and we've added a fix in `jest-haste-map` which we think it's going to fix it. We're going to release a new version of metro with the fix very soon

**Comment by Fi2zz** [comment]
this problem still presents  at version 0.48


BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::1 - - [11/Oct/2018:05:00:38 +0000] "GET /index.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "chat/1 CFNetwork/974.2.1 Darwin/17.7.0"
error: bundling failed: ReferenceError: SHA-1 for file /Users/fitz/WORKSPACE/examples/index.js is not computed
    at DependencyGraph.getSha1 (/Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:222:119)
    at /Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:110:26
    at Generator.next (<anonymous>)
    at step (/Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:11:657)
    at /Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:11:887
    at new Promise (<anonymous>)
    at /Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:11:568
    at Transformer.transformFile (/Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:133:16)
    at /Users/fitz/WORKSPACE/examples/node_modules/react-native/node_modules/metro/src/Bundler.js:54:34
    at Generator.next (<anonymous>)

**Comment by jsmankoo** [comment]
I'm having the same issue on v0.49.

**Comment by ahilles107** [comment]
I have this issue also.

```warning: the transform cache was reset.
Loading dependency graph, done.
Loading dependency graph...
SHA-1 for file /Users/pawelmikolajczuk/Projects/asystentciazy/index.js is not computed

ReferenceError: SHA-1 for file /Users/pawelmikolajczuk/Projects/asystentciazy/index.js is not computed
    at DependencyGraph.getSha1 (/Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/node-haste/DependencyGraph.js:201:13)
    at /Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/DeltaBundler/Transformer.js:164:26
    at Generator.next (<anonymous>)
    at step (/Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/DeltaBundler/Transformer.js:31:30)
    at /Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/DeltaBundler/Transformer.js:50:14
    at new Promise (<anonymous>)
    at /Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/DeltaBundler/Transformer.js:28:12
    at Transformer.transformFile (/Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/DeltaBundler/Transformer.js:188:7)
    at /Users/pawelmikolajczuk/Projects/asystentciazy/node_modules/metro/src/Bundler.js:78:34
    at Generator.next (<anonymous>)
```

```  
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 50.72 MB / 16.00 GB
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/opt/node@8/bin/node
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: ~0.57.5 => 0.57.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7```

**Comment by synoumar** [comment]
Where is the solution?????
