### ISSUE TITLE
Error when bundling with dev=false because of constant-folding-plugin

### ISSUE THREAD

**Issue by janicduplessis** [facebook/metro#177]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Errors with the following message

```
{"type":"TransformError","lineNumber":0,"errors":[{"description":"/Users/janic/Developer/th3rdwave/app/node_modules/react-navigation/src/views/withOrientation.js: Cannot read property 'name' of null","lineNumber":0}],"name":"SyntaxError","message":"/Users/janic/Developer/th3rdwave/app/node_modules/react-navigation/src/views/withOrientation.js: Cannot read property 'name' of null","stack":"TypeError: Cannot read property 'name' of null\n    at PluginPass.exit (/Users/janic/Developer/th3rdwave/app/node_modules/metro/src/JSTransformer/worker/constant-folding-plugin.js:35:58)\n    at NodePath._call (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/path/context.js:65:20)\n    at NodePath.call (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/path/context.js:40:17)\n    at NodePath.visit (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/path/context.js:109:8)\n    at TraversalContext.visitQueue (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/context.js:142:16)\n    at TraversalContext.visitSingle (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/context.js:102:19)\n    at TraversalContext.visit (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/context.js:182:19)\n    at Function.traverse.node (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/index.js:106:17)\n    at NodePath.visit (/Users/janic/Developer/th3rdwave/app/node_modules/@babel/traverse/lib/path/context.js:107:18)"}
```

when bundling this file in release mode

```
import React from 'react';
import { Dimensions } from 'react-native';
import hoistNonReactStatic from 'hoist-non-react-statics';

export const isOrientationLandscape = ({ width, height }) => width > height;

export default function(WrappedComponent) {
  class withOrientation extends React.Component {
    constructor() {
      super();

      const isLandscape = isOrientationLandscape(Dimensions.get('window'));
      this.state = { isLandscape };
    }

    componentDidMount() {
      Dimensions.addEventListener('change', this.handleOrientationChange);
    }

    componentWillUnmount() {
      Dimensions.removeEventListener('change', this.handleOrientationChange);
    }

    handleOrientationChange = ({ window }) => {
      const isLandscape = isOrientationLandscape(window);
      this.setState({ isLandscape });
    };

    render() {
      return <WrappedComponent {...this.props} {...this.state} />;
    }
  }

  return hoistNonReactStatic(withOrientation, WrappedComponent);
}

```

**What is the expected behavior?**

Bundle succeeds

Changing https://github.com/facebook/metro/blob/master/packages/metro/src/JSTransformer/worker/constant-folding-plugin.js#L35 to `const binding = path.node.id && path.scope.getBinding(path.node.id.name);` does fix the issue but I'm unsure if it is the proper fix.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

metro@0.38

**Comment by janicduplessis** [comment]
cc @mjesun

**Comment by janicduplessis** [comment]
@mjesun Sure, there you go https://github.com/facebook/metro/pull/178!
