### ISSUE TITLE
[RN] Metro config is no longer optional

### ISSUE THREAD

**Issue by janicduplessis** [facebook/metro#214]
RN CI currently fails with

```
(node:3341) UnhandledPromiseRejectionWarning: Error: Could not find configuration for metro, did you create a 'metro.config.js'?
    at /private/tmp/react-native-8DEOpVT4/EndToEndTest/node_modules/metro-config/src/loadConfig.js:139:13
    at Generator.next (<anonymous>)
    at step (/private/tmp/react-native-8DEOpVT4/EndToEndTest/node_modules/metro-config/src/loadConfig.js:253:447)
    at /private/tmp/react-native-8DEOpVT4/EndToEndTest/node_modules/metro-config/src/loadConfig.js:253:607
    at <anonymous>
```

Not sure if this is intentional or not but I think it should still work without a config file.

cc @CompuIves @rafeca

**Comment by kelset** [comment]
Possibly related? https://github.com/facebook/react-native/commit/140b230e84f2a5aecdacbcd8527bef370460464d

**Comment by rafeca** [comment]
@CompuIves has a fix for this which is currently landing ✌️
