### ISSUE TITLE
Metro and node-haste looking for node_modules in muliple wrong places

### ISSUE THREAD

**Issue by maximus123123** [facebook/metro#361]
I am using react native, and this is the bundler error I get.
It looks for package.json in myapp/src/services, myapp/src, myapp/ and even outside the root project of the app

error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/USER/work/MYAPP/src/services/node_modules'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getDirFiles (/Users/USER/work/MYAPP/node_modules/metro/src/node-haste/DependencyGraph.js:103:34)
    at Map.AssetResolutionCache.dirPath [as _factory] (/Users/USER/work/MYAPP/node_modules/metro/src/node-haste/AssetResolutionCache.js:41:36)
    at Map.get (/Users/USER/work/MYAPP/node_modules/metro/src/node-haste/lib/MapWithDefaults.js:25:24)
    at AssetResolutionCache.resolve (/Users/USER/work/MYAPP/node_modules/metro/src/node-haste/AssetResolutionCache.js:91:43)
    at resolveAsset (/Users/USER/work/MYAPP/node_modules/metro/src/node-haste/DependencyGraph.js:227:36)
    at resolveAssetFiles (/Users/USER/work/MYAPP/node_modules/metro/node_modules/metro-resolver/src/resolve.js:456:22)
    at resolveFile (/Users/USER/work/MYAPP/node_modules/metro/node_modules/metro-resolver/src/resolve.js:342:20)
    at resolveFileOrDir (/Users/USER/work/MYAPP/node_modules/metro/node_modules/metro-resolver/src/resolve.js:255:22)
    at Object.resolve (/Users/USER/work/MYAPP/node_modules/metro/node_modules/metro-resolver/src/resolve.js:148:20)

**Comment by maximus123123** [comment]
Okey, solved it, but not without losing a few hairs

the problem was 
`require('some kind image.png')`

instead of:
`require('./some image.png')`

No idea why it wouldn't say:
module not: some image.png 

instead it will eternally look for node_modules in every folder down all the way up to root (true root, not project root)
