### ISSUE TITLE
bundling failed: ReferenceError: SHA-1 for file .../node_modules/lodash.zip is not computed

### ISSUE THREAD

**Issue by IgorBelyayev** [facebook/metro#441]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Including [`lodash.zip`](https://www.npmjs.com/package/lodash.zip) as a dependency in my React-Native project causes the following error to be thrown by the metro bundler:

```
error: bundling failed: ReferenceError: SHA-1 for file /my_project_dir/node_modules/lodash.zip (/my_project_dir/node_modules/lodash.zip) is not computed
    at DependencyGraph.getSha1 (/my_project_dir/node_modules/metro/src/node-haste/DependencyGraph.js:259:13)
    at /my_project_dir/node_modules/metro/src/DeltaBundler/Transformer.js:211:26
    ...
```

My guess is that because the folder in `node_modules` for this particular dependency happens to be called something with '.zip' in it (`lodash.zip`), the bundler erroneously thinks that it is some sort of .zip file that it needs to check.

I am using metro version `0.54.1` which is the version used in the latest version of React-Native (`0.60.4`).

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
1) Be in any React-Native project using RN `0.60.4` (metro version `0.54.1`)
2) `yarn add lodash.zip`
3) `react-native run-android`
4) Observe error described above.

**What is the expected behavior?**
The metro bundler should not fail bundling.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
Metro configuration:
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```
Metro version: `0.54.1`
node: `12.4.0`
yarn: `1.13.0`
operating system: macOS Mojave `10.14.5`

**Comment by esutton** [comment]
A related or duplicate issue: https://github.com/facebook/metro/issues/330

`SHA-1 for file ... is not computed` when using `resolver.resolveRequest`

It has a work-around.  However, I am using react-native and cannot figure out how to apply since I do not include metro directly in my package.json

**Comment by jkirkpatrick24** [comment]
I'm coming across this issue as well. @IgorBelyayev did you come up with a workaround?

**Comment by IgorBelyayev** [comment]
@jkirkpatrick24 Yes, instead of using [`lodash.zip`](https://www.npmjs.com/package/lodash.zip) in my dependencies, I just used the full [`lodash`](https://www.npmjs.com/package/lodash) library and imported `zip` from it.

**Comment by jkirkpatrick24** [comment]
Ah, in my case this is a dependency of another module. I'd be happy to take a crack at a PR to fix this but would probably need some guidance on where to look in the codebase.
