### ISSUE TITLE
Cannot start App: Error: Cannot find module 'metro/src/DeltaBundler/Worker'

### ISSUE THREAD

**Issue by mrousavy** [facebook/metro#581]
## Bug Report

When I start the Metro server I get the following error output:

```
Failed to construct transformer:  Error: Cannot find module 'metro/src/DeltaBundler/Worker'
Require stack:
- /Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/base/BaseWorkerPool.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/WorkerPool.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/index.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/WorkerFarm.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/Transformer.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/Bundler.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/IncrementalBundler.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/index.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/start/start.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/cli.js
- /Users/mrousavy/.config/yarn/global/node_modules/react-native-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.resolve (internal/modules/cjs/helpers.js:81:19)
    at new BaseWorkerPool (/Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/base/BaseWorkerPool.js:65:28)
    at new WorkerPool (/Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new JestWorker (/Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/index.js:131:26)
    at WorkerFarm._makeFarm (/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/WorkerFarm.js:152:12)
    at new WorkerFarm (/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/WorkerFarm.js:87:27)
    at new Transformer (/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/Transformer.js:146:24)
    at /Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/Bundler.js:54:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/base/BaseWorkerPool.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/WorkerPool.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/jest-worker/build/index.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/WorkerFarm.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/Transformer.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/Bundler.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/IncrementalBundler.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/node_modules/metro/src/index.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/start/runServer.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/start/start.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js',
    '/Users/mrousavy/Projects/Springsale/app/node_modules/react-native/cli.js',
    '/Users/mrousavy/.config/yarn/global/node_modules/react-native-cli/index.js'
  ]
}
```

**What is the current behavior?**

App is not starting:

<img src="https://user-images.githubusercontent.com/15199031/89805375-d5816c80-db35-11ea-8253-8dc171b6d8ef.png" width="50%">

**What is the expected behavior?**

App should run.

### Versions

* `npx react-native --version`: 4.10.1
* react-native: 0.63.2
* metro-react-native-babel-preset: 0.61.0, but same issue occurs with 0.62.0

**Comment by mrousavy** [comment]
I had to install `metro-config` 0.58.

**Comment by olalonde** [comment]
Had the same issue after creating a new project with `npm create -- expo-app --example "with-typescript" mobile-app`:

```
$ npm run web
...
(node:40310) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
web compiled successfully
Failed to construct transformer:  Error: Cannot find module 'metro/src/DeltaBundler/Worker'
Require stack:
- /Users/redacted/code/monorepo/node_modules/jest-worker/build/base/BaseWorkerPool.js
```

**Comment by olalonde** [comment]
Seems like a bug? Should re-open the issue...

**Comment by olalonde** [comment]
Related issue: https://github.com/facebook/metro/issues/293
