### ISSUE TITLE
metro-minify-terser: TypeError: Cannot read property 'match' of undefined 

### ISSUE THREAD

**Issue by wbroek** [facebook/metro#767]
**Do you want to request a *feature* or report a *bug*?**
Bug on _metro-minify-terser_
**What is the current behavior?**
When using the last version of _metro-minify-terser_ (0.67.0) as the minifier for Metro in my React Native project the bundling will fail:
```
error index.js: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at countLines (/Users/wouter/stack/Projects/Vaxcards/VaxCards/node_modules/metro/src/lib/countLines.js:17:23)
    at transformJS (/Users/wouter/stack/Projects/Vaxcards/VaxCards/node_modules/metro-transform-worker/src/index.js:332:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async transformJSWithBabel (/Users/wouter/stack/Projects/Vaxcards/VaxCards/node_modules/metro-transform-worker/src/index.js:408:10)
    at async Object.transform (/Users/wouter/stack/Projects/Vaxcards/VaxCards/node_modules/metro-transform-worker/src/index.js:569:12)
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
- Create a react native project (`npx react-native init AwesomeProject`)
- Add _metro-minify-terser_ to the project ('npm install metro-minify-terser --save-dev`)
- Modify the `metro.config.js` and add the transformer (see config below)
- Bundle or build the app (`npx react-native bundle`)

**What is the expected behavior?**
Bundle or build 

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
_package.json_
```
"devDependencies": {
    "@babel/core": "^7.16.12",
    "@babel/runtime": "^7.16.7",
    "babel-jest": "^27.4.6",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "7.32.0",
    "jest": "^27.4.7",
    "metro-minify-terser": "^0.67.0",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-native-codegen": "0.0.13",
    "react-test-renderer": "17.0.2"
 }
```
_metro.config/js_
```
const defaultSourceExts =
  require('metro-config/src/defaults/defaults').sourceExts;

module.exports = {
  serializer: {
    processModuleFilter: module => {
      return !module.path.endsWith(
        'react-native/Libraries/Renderer/implementations/ReactFabric-prod.js',
      );
    },
  },

  transformer: {
    minifierPath: require.resolve('metro-minify-terser'),
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: true,
      },
    }),
  },

  resolver: {
    sourceExts: process.env.RN_SRC_EXT
      ? [...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts), 'cjs']
      : [...defaultSourceExts, 'cjs'],
  },
};
```
environment
```
 System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 25, 26, 27, 28, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
```

**Comment by rh389** [comment]
Hi @wbroek - `metro-minify-terser@0.67.0` requires metro 0.67 (specifically, [support for async minifiers](https://github.com/facebook/metro/commit/216e0a2cfc9bdac1297b338976e5319ab79c9e23) introduced by `metro-transform-worker@0.67.0`). 

I presume you're using metro 0.66 as that's the version that comes with the latest RN (coincidentally, and admittedly confusingly, currently also at 0.67), via `react-native-community/cli@^6.0.0`. You can confirm that with `npx metro --version`.

For now I'd advise rolling back `metro-minify-terser` to match metro's version. I'll look into making this clearer.
