### ISSUE TITLE
Custom `resolveRequest` example from the docs fails

### ISSUE THREAD

**Issue by krystofwoldrich** [facebook/metro#891]
**Do you want to request a *feature* or report a *bug*?**
I'm reporting a *bug*. I would like to use custom module resolver, but even simple example which should just use the default function fails.

`metro.config.js`
```js
module.exports = {
  resolver: {
    resolveRequest: (context, moduleName, platform) => {
      // Optionally, chain to the standard Metro resolver.
      return context.resolveRequest(context, moduleName, platform);
    }
  },
```

**What is the current behavior?**
Current error

```bash
 ❯ npx react-native bundle \
  --dev false \
  --platform android \
  --entry-file index.js \
  --reset-cache \
  --bundle-output index.android.bundle \
  --sourcemap-output index.android.bundle.map
defaultConfig undefined
/Users/krystofwoldrich/repos/sentry-react-native/sample
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


error Unable to resolve module ./src/App from /Users/krystofwoldrich/repos/sentry-react-native/sample/index.js: ./src/App could not be found within the project or in these directories:
  node_modules
  ../node_modules
  /Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/src/App

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
   6 | import 'react-native-gesture-handler';
   7 |
>  8 | import App from './src/App';
     |                  ^
   9 | import {name as appName} from './app.json';
  10 |
  11 | AppRegistry.registerComponent(appName, () => App);.
Error: Unable to resolve module ./src/App from /Users/krystofwoldrich/repos/sentry-react-native/sample/index.js: ./src/App could not be found within the project or in these directories:
  node_modules
  ../node_modules
  /Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/src/App

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
   6 | import 'react-native-gesture-handler';
   7 |
>  8 | import App from './src/App';
     |                  ^
   9 | import {name as appName} from './app.json';
  10 |
  11 | AppRegistry.registerComponent(appName, () => App);
    at ModuleResolver.resolveDependency (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async traverseDependenciesForSingleFile (/Users/krystofwoldrich/repos/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
info Run CLI with --verbose flag for more details.
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

To reproduce copy the example `resolveRequest` into your config and run the bundle command.

```bash
npx react-native bundle \
  --dev false \
  --platform android \
  --entry-file index.js \
  --reset-cache \
  --bundle-output index.android.bundle \
  --sourcemap-output index.android.bundle.map
```

**What is the expected behavior?**

Metro creates a bundle as it does without the custom `resolveRequest`.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

The whole [metro config](https://github.com/getsentry/sentry-react-native/blob/e99d97badabb31ec095bfd33f9379cc8a52bae97/sample/metro.config.js) without the custom resolver.

Metro version: 0.66.2
Node version: v16.17.1
Yarn version: 1.22.19
macOS 12.6

**Comment by motiz88** [comment]
Hey @krystofwoldrich, thanks for reporting this. You are using an old version of Metro where the `resolveRequest` API was different (it took slightly different parameters & had no chaining via `context.resolveRequest`). The change happened in d81d8877c05637eac2b4ea946a9fa1e8ae869b06 (released in [v0.68.0](https://github.com/facebook/metro/releases/tag/v0.68.0)). You can look at [the old version's documentation](https://github.com/facebook/metro/blob/ccfec1e846cc8f6ab5efe9add821abbf4a5e4ead/docs/Configuration.md#resolverequest) to see an example of the old API, but I'd recommend upgrading Metro in your project as the best fix (ideally by upgrading React Native to a newer version, which ships with a compatible Metro).
